baseURL: "https://defmarco.com/"
title: "defmarco.com"
author: "Marco Schneider"
languageCode: 'en-us'
paginate: 5
DefaultContentLanguage: "en"
enableInlineShortcodes: true

theme: "paper"

params:
  color: "gray"
  twitter: "eskape"
  github: "neshtea"
  mastodon: "https://chaos.social/@anarres"
  linkedin: "marco-schneider-34391612a"
  avatar: "marco.schneider@posteo.de"

permalinks:
  notes: /note/:year:month:day

markup:
  highlight:
    style: "rose-pine"
    linenos: true
    anchorlinenos: true
    noClasses: false

menu:
  main:
    - identifier: about
      name: About
      url: "/about"
    - identifier: posts
      name: Posts
      url: "/posts"
    - identifier: code
      name: "Code"
      url: "/code"
    - identifier: "talks+posts"
      name: Talks+Posts
      url: "/talks-and-posts"
